프로젝트 생성
f-lab-edu/hotel-java pull request #1
Opened 2023-02-24 16:17 UTC by korjun1993

Gradle 빌드툴을 이용해 프로젝트를 생성하였습니다.

2023-02-25 08:54 UTC, f-lab-lyan requested changes
제가 아마도 깜빡한 것 같은데, Gradle multi-module로 구성하면 좋을 것 같습니다. 지금은 아마도 하나의 submodule만 생기게 될 텐데요. multi-module로 진행하는 이유는 추후에 설명하기로 하고, 일단 multi-module구조로 변경해 주시면 좋을 것 같습니다.

2023-02-25 08:54 UTC, f-lab-lyan commented on .gitignore
> +application-mariadb.properties
마지막 줄에

<img width="330" alt="image" src="https://user-images.githubusercontent.com/90605505/221348079-1e14569e-28e2-4bc3-a5a1-ea20b742742f.png">

이거 해결해 주세요.

2023-02-25 08:54 UTC, f-lab-lyan commented on .gitignore
> +application-mariadb.properties
이 파일에서 실제로 필요한 애들만 남기고 다 지워주시겠어요? 어떤게 필요할지 생각해 보시면 좋을 것 같습니다.

2023-02-25 08:54 UTC, f-lab-lyan commented on build.gradle
> +}
dependencies도 필요없다면, 지우면 될 것 같은데요. 스프링 부트 프로젝트를 실행하기 위한 최소한의 설정은 들어가면 좋을 것 같습니다.

2023-02-26 08:40 UTC, korjun1993 commented on .gitignore
> +application-mariadb.properties
네 해결했습니다. EOF가 있고 없고의 차이에 대해 생각해본 적이 없었네요.
궁금해서 EOF를 넣어주는 이유를 알아봤습니다.
예전의 POSIX 규칙에서는 EOF가 있는 파일과 없는 파일이 뒤섞이면, 예기치 않는 에러가 발생할 수 있기 때문에
이를 대비하기 위해 EOF가 없을 경우, 컴파일 에러를 냈었다고 합니다.


Intellij에서 다음 설정을 체크하면 파일의 끝에 EOF를 자동으로 추가해준다고 합니다.
![image](https://user-images.githubusercontent.com/45716246/221400336-8066d17e-0274-4b23-8c69-bc77da91035d.png)

2023-02-27 09:14 UTC, f-lab-lyan commented on app/src/test/java/com/example/AppTest.java
> +    @Test public void appHasAGreeting() {
nit: 어노테이션을 붙이면, 한칸을 내리는 게 좋지 않을까요? 변수일 경우에는 그래도 괜찮을 것 같긴한데, 메소드면, 이렇게는 잘 안 사용하는 것 같습니다.

2023-02-27 09:16 UTC, f-lab-lyan commented on app/src/main/java/com/example/App.java
> +public class App {
스프링 어플리케이션의 경우 보통 AppApplication과 같이 뒤에 Application을 붙이는데요. 이 부분에 대해서도 어떻게 할지 생각해 보시면 좋을 것 같습니다. cc/ @korjun1993 @DevKTak

2023-02-27 10:58 UTC, DevKTak commented on app/src/test/java/com/example/AppTest.java
> +    @Test public void appHasAGreeting() {
```suggestion
    @Test 
    public void appHasAGreeting() {
```

2023-02-27 12:11 UTC, korjun1993 commented on app/src/test/java/com/example/AppTest.java
> +    @Test public void appHasAGreeting() {
네 알겠습니다. gradle init 으로 프로젝트를 만들고, 이런 부분까지 살펴보지 않았네요.

2023-02-28 09:16 UTC, f-lab-lyan commented
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/90605505/221807458-258ddc89-387a-46e6-93ca-6df173548ca5.png">

확인했습니다. 신기하네요. ㅎㅎ

2023-02-28 09:17 UTC, f-lab-lyan requested changes

2023-02-28 09:17 UTC, f-lab-lyan commented on app/src/main/java/com/example/HotelJavaApplication.java
> +public class HotelJavaApplication {
스프링 어플리케이션 어노테이션 추가 부탁 드립니다. :-)

2023-02-28 09:17 UTC, f-lab-lyan commented on app/src/test/java/com/example/HotelJavaApplicationTest.java
> +public class HotelJavaApplicationTest {
이 테스트는 필요없을 것 같아요. 대신 컨트롤러 테스트나 다른 테스트를 추가해보죠.

2023-02-28 15:42 UTC, korjun1993 commented on app/src/main/java/com/example/HotelJavaApplication.java
> +public class HotelJavaApplication {
네 추가했습니다 😄

2023-02-28 15:43 UTC, korjun1993 commented on app/src/test/java/com/example/HotelJavaApplicationTest.java
> +public class HotelJavaApplicationTest {
네 경탁님과 API 의논후에 컨트롤러 및 테스트코드 짜서 올리도록 하겠습니다.

2023-03-02 03:08 UTC, merged