[#8] 회원 로그인 기능 구현
f-lab-edu/hotel-java pull request #11
Opened 2023-04-04 19:12 UTC by korjun1993

# 🎯  주요작업내용
- [x] 스프링 시큐리티 프레임워크를 이용하여 Email, Password 기반 인증 기능 구현
- [ ] 모든 요청을 403으로 응답하는 문제 해결
- [ ] 인증 통과한 사용자에게 JWT 토큰 발급 기능 구현
- [ ] 요청 헤더에 JWT 토큰이 있을 경우, 토큰 기반 인증 기능 구현 

# ❓ 궁금한점
- 인증 과정을 통과한 Authentication을 SecurityContextHolder에 저장한다고 공부했습니다. In-memory session에 저장하는 것과 무엇이 다른가요?
- 로그인을 정상적으로 수행한 회원이라면, SecurityContextHolder에 Authentication이 존재할텐데요. 이 경우, SecurityContextHolder 를 살펴보고 Authentication이 없다면 증 절차를 스킵하나요?

2023-04-04 23:05 UTC, f-lab-scott approved these changes
몇 가지 빈칸이 있긴 하지만, 작업중이시므로 당연히 채워질 거라 생각합니다. 👍 
수고 많으셨고 방향성이 좋습니다. 그대로 진행하시면 될듯합니다. 💯

2023-04-04 23:05 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/HotelJavaApplication.java
> +  }
`@SpringBootApplication` 이 자동으로 컴포넌트 스캔 해서 빈 등록하는 것들 중 일부입니다.
별도의 커스터마이제이션을 하실 것이 아니라면, 이렇게 등록된 것을 그대로 사용하시면 됩니다.
https://sabarada.tistory.com/236

2023-04-04 23:05 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/security/provider/MemberDetailsAuthenticationProvider.java
> +  private final BCryptPasswordEncoder passwordEncoder;
여기서도 `PasswordEncoder` 로 사용해주세요

2023-04-04 23:09 UTC, f-lab-scott commented
질문에 대한 답변 드립니다. 

>  인증 과정을 통과한 Authentication을 SecurityContextHolder에 저장한다고 공부했습니다. In-memory session에 저장하는 것과 무엇이 다른가요?

- 저장 메카니즘에 관한 질문이라면 `ThreadLocal` 에 대해 학습해 보시기를 권합니다.

> 로그인을 정상적으로 수행한 회원이라면, SecurityContextHolder에 Authentication이 존재할텐데요. 이 경우, SecurityContextHolder 를 살펴보고 Authentication이 없다면 증 절차를 스킵하나요?

- JWT 기반 인증 플로우에서는 요청이 들어올때마다 `SecurityContextHolder` 가 비워져야 합니다. HTTP의 "무상태성" 에 대해 생각해 보시기 바랍니다. 들어온 요청을 처리할 때는 앞선 요청을 처리한 맥락이 서버 사이드에서 사라져 있어야 합니다(이걸 쿠키를 통해 우회하게 해 주는 것이 "세션" 입니다). 따라서 로그인을 수행했다는 것은 "JWT가 발급되었다" 는 것이고, JWT를 관리하는 책임은 온전히 클라이언트가 갖고 있으며, 클라이언트는 후속 요청들에 대해 JWT를 헤더로 계속 들고 다니며 서버에게 자기 자신을 증명하는 겁니다.

만약 인증이 필요한 엔드포인트에 JWT가 없이 방문한 클라이언트가 있다면 401 or 403을 응답하시면 됩니다.

요약하면 질문하신 상황과 같이 `SecurityContextHolder` 에 `Authentication` 이 필터 로직부터 존재하는 경우는 없습니다.

> 테스트는 통합테스트로 진행해야하나요?

- 지금은 필터 개별에 대한 단위 테스트를 하셔도 되지만 나중에 security config 전체가 잘 돌아가는지를 보려면 통합테스트가 필수적이겠죠?

2023-04-05 01:52 UTC, korjun1993 commented on app/src/main/java/com/hotelJava/HotelJavaApplication.java
> +  public BCryptPasswordEncoder passwordEncoder() {
넵 놓치고 있던 부분이었네요! 감사합니다

2023-04-05 06:17 UTC, korjun1993 commented on app/src/main/java/com/hotelJava/HotelJavaApplication.java
> +  }
자동으로 등록되는 빈이었군요! 😄

2023-04-06 06:28 UTC, f-lab-scott approved these changes
👍 수고하셨습니다. 필요하신 때에 머지 진행 부탁드립니다.

2023-04-14 09:59 UTC, wheejuni requested changes
하나만 시도해보고 머지 가시죠

2023-04-14 09:59 UTC, wheejuni commented on app/src/main/java/com/hotelJava/security/config/JwtConfig.java
> +}
이 값을 `application.properties` 를 통해 관리될 수 있도록 수정 부탁드립니다.
https://sgc109.github.io/2020/07/07/spring-boot-configuration-properties/

2023-04-14 18:13 UTC, korjun1993 commented on app/src/main/java/com/hotelJava/security/config/JwtConfig.java
> +}
넵 처음에 설정파일로 했었다가 근거가 없다는 생각에 클래스로 바꿨었습니다. 멘토님께서 설정파일을 선호하는 이유, 언제 사용하는지 알고 싶습니다.

2023-04-16 16:58 UTC, merged