[#18] 숙소 수정
f-lab-edu/hotel-java pull request #19
Opened 2023-04-16 11:25 UTC by DevKTak

## 작업 내용
- 숙소 정보 수정 로직 구현
- 숙소 정보 수정 테스트 코드 구현

2023-04-16 12:35 UTC, wheejuni commented on app/src/main/java/com/hotelJava/accommodation/service/AccommodationService.java
> +        pictureMapper.toEntity(updateAccommodationRequestDto.getPictureDto()),
```kotlin
val accommodation = accommodation.updateAccommodation(
     name = dto.getName()
    type = dto.getType()
....
)

2023-04-16 12:40 UTC, wheejuni approved these changes

2023-04-18 22:49 UTC, f-lab-scott requested changes

2023-04-18 22:49 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/controller/AccommodationController.java
> +  public HttpStatus updateAccommodation(@PathVariable String encodedAccommodationId,
네 요런 형태도 좋긴 한데 타입이 단순 스트링은 아니었으면 좋겠습니다.
그런데 지금 단계에선 이정도 구현도 충분한 거 같아요 ㅎㅎ 수고하셨습니다.

이외에도 컨플릭트 하나 있네요. 체크해주세요~

2023-04-19 03:22 UTC, merged