jwt 기반 로그인 기능
f-lab-edu/hotel-java pull request #35
Opened 2023-04-17 06:57 UTC by korjun1993

2023-04-19 22:56 UTC, wheejuni requested changes
간단한 통합 테스트가 추가되었으면 좋겠습니다. 👍 
먼저 호준 님이 고민하고 작성해보시고, 너무 막막하다 느껴지시면 제가 예제 코드를 드릴게요
수고하셨습니다.

2023-04-19 22:56 UTC, wheejuni commented on app/src/main/java/com/hotelJava/security/config/JwtConfigurationProperties.java
> +public record JwtConfigurationProperties(String issuer, String secret, Duration validityTime) {}
`record` 활용까지 너무 좋네요 👍

2023-04-19 22:56 UTC, wheejuni commented on app/src/main/java/com/hotelJava/security/filter/JwtAuthenticationFilter.java
> +    String jwtToken = request.getHeader("Authorization");
Bearer Auth에 대해 학습하시고, HTTP 표준에 맞게 구현해 주셔도 좋을 듯 합니다.

2023-04-20 02:37 UTC, korjun1993 commented on app/src/main/java/com/hotelJava/security/filter/JwtAuthenticationFilter.java
> +    String jwtToken = request.getHeader("Authorization");
넵 Bearer Auth가 뭔지 찾아보겠습니다! 감사합니다.

2023-04-20 02:38 UTC, merged