[#4] 회원가입 기능 구현
f-lab-edu/hotel-java pull request #5
Opened 2023-03-23 17:12 UTC by korjun1993

## 🎯 주요 작업 내용
- 공통 응답 API 수정
   - API 호출 성공 시 클라이언트에게 응답할 데이터가 없는 경우, 사용할 메서드를 추가했습니다. 
- 회원가입 기능 추가
   - Member 도메인 추가   
   - MemberController, MemberService, MemberRepository 추가

## ❓ 궁금한 점
- memberService.signUp() 메서드 내부에서는 중복검사를 안해줘도 될까요?
- memberController.signUp() 메서드 내부에서 중복검사를 수행하였을 때, Email이 중복일 경우 예외를 발생시키는 방법으로 구현해도 되나요? 어떤 상황일 때 예외를 활용하는게 좋을까요? [블로그](https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/)를 읽어봤는데 헷갈리네요.
- MemberServiceTest 클래스에서 isDuplicated()를 테스트하는 코드는 signUp()에 의존하고 있는 걸로 보입니다. 만약에 signUp() 기능이 잘못 동작한다면, isDuplicated() 를 올바르게 테스트할 수 없을 것 같다는 생각이 듭니다. isDuplicated()만 잘 동작하는지 확인하고 싶은데, 이럴 땐 어떻게 해야하나요?

2023-03-24 13:19 UTC, f-lab-scott requested changes
몇 가지 의견 드립니다. 일요일날에도 같이 말씀 나눠보시죠.

2023-03-24 13:19 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/controller/MemberController.java
> +    }
중복이 발생하면 그냥 Exception을 던지고  `@ControllerAdvice` 로 묶어서 처리하는 형태면 어떨지 제안하고 싶습니다.
https://jeong-pro.tistory.com/195

2023-03-24 13:19 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/controller/MemberController.java
> +    memberService.signUp(signUpDto.toEntity());
위 처럼 예외 핸들링이 되면, 이 메소드에 그냥 DTO를 통째로 던져도 될 것 같고요.

2023-03-24 13:19 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/domain/Member.java
> +  private String phone;
대문자여야만 하나요?

2023-03-24 13:19 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/dto/SignUpRequestDto.java
> +  }
DTO에서 모델 클래스에 의존성을 갖는 것이 바람직한지는 저도 잘 모르겠어요.
이게 워낙 설계는 천차만별이라, 저도 확신을 갖고 말씀드리긴 어려운데요. 의존성이 없으면 좋지 않을까 하는 생각은 있습니다.

2023-03-24 13:19 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/repository/MemberRepository.java
> +public class MemberRepository {
`JpaRepository` 사용하면 안 되려나요?

2023-03-24 13:53 UTC, korjun1993 commented on app/src/main/java/com/hotelJava/member/repository/MemberRepository.java
> +public class MemberRepository {
의견 감사합니다! JpaRepository 학습한 후에 적용해보도록 하겠습니다.

2023-03-24 14:17 UTC, korjun1993 commented on app/src/main/java/com/hotelJava/member/dto/SignUpRequestDto.java
> +  }
제가 이번 주에 많은 고민을 한 부분이고 Dto, Domain의 차이를 몰랐기 때문에 이 부분을 먼저 학습했습니다.
- Dto는 Layer 간에 데이터를 옮기는 수단입니다.
- 반면에 Domain은 핵심 비즈니스 로직을 담는 객체입니다.

학습한 내용을 프로젝트에 적용해봤습니다.
- `SignUpRequestDto`: 사용자가 회원가입 요청 메시지에 담은 데이터를 Controller에서 사용하고 싶어서 객체로 만들어야겠다는 생각을 했습니다. 해당 객체를 Dto로 구분했고 회원가입에 필요한 필드만 갖고 있을 뿐입니다.
- `Member`: 사용자의 모든 필드를 갖고 있으며, 핵심 로직을 갖고 있는 객체입니다.

Dto와 Domain으로 분리하다보니 문제가 생겼습니다. 결국 Dto를 가공하여 Domain으로 변경한 후 로직을 수행해야 한다는 점입니다. 그래서 Dto를 Domain으로 변경하는 메소드 `SignUpRequestDto.toEntity()`를 하나 만들어주었습니다.

### ❓ 궁금한 점
제가 Dto, Domain을 분리한 이유가 합당한지, Dto를 Domain으로 변경하고자 할 때 둘 간의 의존성을 제거하는 것이 가능한지 궁금합니다.

2023-03-24 14:35 UTC, korjun1993 commented on app/src/main/java/com/hotelJava/member/domain/Member.java
> +  private String phone;
일반적으로 DB에서 테이블명과 컬럼명은 대문자를 사용한다고 알고 있습니다. `@Comlum`의 name값을 소문자로 고쳐 쓰고, NamingStrategy를 변경하면 JPA가 알아서 대문자로 쿼리를 작성해줄 것 같습니다. 더 나아가서 `@Column`을 생략해볼까 합니다. 생략되도 Entity의 필드는 전부 자동으로 테이블과 매핑된다고 합니다.

2023-03-24 14:53 UTC, korjun1993 commented on app/src/main/java/com/hotelJava/member/controller/MemberController.java
> +    memberService.signUp(signUpDto.toEntity());
dto를 던지지 않고 entity를 던진 이유가 따로 있는데요. 굉장히 추상적인,,, 말로 설명하기 좀 힘든 이유였는데 이 글의 답변자와 같은 맥락입니다. [인프런 질의 응답 링크](https://www.inflearn.com/questions/53023/dto%EC%9D%98-layer%EC%97%90%EB%8C%80%ED%95%B4-%EC%A7%88%EB%AC%B8-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4)

2023-03-26 01:56 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/dto/SignUpRequestDto.java
> +  }
- Domain -> DTO : 괜찮습니다. 고민하신 부분에 동의합니다.
- DTO -> Domain : 생각해볼 여지가 있습니다. 이것이 DTO layer의 역할일까요? DTO는 변동성이 가장 큰 객체들 중 하나인데, 변동성이 발생할 때마다 핵심 계층인 Domain의 정보까지 다 노출시키며(혹은 그에 좌우되며) 변경해야 합니다. 이것이 좋은 방법인지는 잘 모르겠습니다.
- DTO <-> Domain 간의 의존성을 제거하는 것이 가능한지: 그 사이의 레이어를 두면 서로가 서로를 몰라도 변환이 가능할 겁니다. https://lktprogrammer.tistory.com/42 를 참조해 보시면 좋습니다. 

참고로 저는 도메인 클래스를 설계할때도 노출시키고자 하는 정보들을 그룹핑하여, 그것을 인터페이스로 묶어 놓고 도메인 클래스에선 그것을 구현하는 형태를 갖는 설계를 선호합니다. 

```java

public interface UserContactInfo {
    String getEmail();
}

public class User implements UserContactInfo {
    
    @Override
    public String getEmail() {
    ...

}

public class UserInfoDto implements UserContactInfo {
...
```

2023-03-26 01:57 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/domain/Member.java
> +  private String phone;
@korjun1993 오히려 DB가 호스팅되는 OS에 따라 대소문자 구분이 될 수도, 안 될수도 있어서 소문자로 통일하는 조직과 회사가 많습니다.

2023-03-26 01:57 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/domain/Member.java
> +  private String phone;
저도 그동안 경험한 회사들 중 테이블 이름과 칼럼명을 대문자로만 사용하는 경우는 한번도 보지 못했긴 합니다.

2023-03-26 02:00 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/controller/MemberController.java
> +    memberService.signUp(signUpDto.toEntity());
네... 그러면 Controller -> Service 호출이 바로 이뤄지는 상황에서, 엔티티를 바로 서비스에 던지는 것이 서비스의 재사용성을 높이는 방안이라 보시는 거죠?

그러면 컨트롤러단의 클린함은 어떻게 유지할 수 있을까요? 수많은 DTO들이 개발 단계를 지속하면서 작성될 텐데, 모든 DTO를 작성하실 때마다 `.toEntity()` 구현해야 하는 부담이 뒤따르는 건 덤이겠군요.

2023-03-26 02:03 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/common/dto/ApiResponse.java
> +    this.responseMessage = responseMessage;
"언제든지 공통된 포맷" 에 공감하기 어렵기는 합니다. 두 분간의 합의 사항이라면 이제와서 제가 바꾸는 건 어려울 수 있겠지만요. 아래에 제 생각을 정리해 보겠습니다.

- 각 API마다 응답의 성질이 몹시 다를 것 같습니다. 예를 들어 예약 API와 숙소 검색 API의 데이터의 실질과 형태는 굉장히 큰 차이가 날 것 같습니다. 이때에도 공통된 포맷이 유효한지는 모르겠습니다.
- 만약 공통된 포맷이라는 것이 resp body가 아닌 header를 비롯한 기타 정보라면 이 클래스의 가치가 더 극적으로 떨어집니다. 실질적으로 예외 상황에 대한 공통 응답 처리는 제가 제안드린 방법대로 `@ControllerAdvice` 등을 사용해 충분히 풀어낼 수 있고, 정상 응답의 경우에도 `ResponseEntity` 라는, 스프링이 제공하는 사용성 좋은 공통 응답 클래스가 있습니다(이 클래스가 MessageConverter를 통해 응답으로 직렬화됩니다).

2023-03-26 02:05 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/common/dto/ApiResponse.java
> +    this.responseMessage = responseMessage;
또한 이 클래스를 사용하는 것이 굳이 resp body가 없어도 되는 상황에도 억지로 바디를 만들어 내리는 역효과를 낼 수도 있겠다고 생각합니다. 
상태 코드를 풍부히 활용하면 Create 성 API들의 작동에도 충분히 의미가 담긴 응답들을 내릴 수 있습니다.

2023-03-26 03:58 UTC, korjun1993 commented on app/src/main/java/com/hotelJava/member/controller/MemberController.java
> +    memberService.signUp(signUpDto.toEntity());
네.. 재사용성을 높이기 위해서 entity를 인자로 받았습니다. 하지만 멘토님 말씀대로 dto마다 toEntity()를 만들어야하니 부담이 너무 크네요. 현실적으로 service 계층의 재사용성을 낮추고 dto를 인자로 받는게 나을 것 같습니다.

2023-03-26 12:19 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/common/dto/ApiResponse.java
> +    this.responseMessage = responseMessage;
- 이 클래스는 삭제하는 것으로 결정

2023-03-26 12:35 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/repository/MemberRepository.java
> +    }
`Optional<T>` 활용해 보시는 건 어떨까요?

2023-03-30 14:51 UTC, f-lab-scott requested changes
두 가지만 체크 부탁드립니다 🙇

2023-03-30 14:51 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/error/MemberExceptionHandler.java
> +    return DuplicateEmailFound;
static method를 활용해주시다 보니 이 리턴이 조금 뜬금없다는 생각이 듭니다.
정황상 Enum 중 하나로 보여지는데 어떤 enum인지 파악하는데 좀 오래 걸리겠단 생각이 들어요.
그래서 enum의 경우 저는 static import를 지양하기는 합니다.

2023-03-30 14:51 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/member/error/errorCode/MemberErrorCode.java
> +  DuplicateEmailFound(409, "Email already exists");
enum의 네이밍 컨벤션에 대해 좀 더 학습해 보시길 권합니다.

`DUPLICATED_EMAIL_FOUND` 와 같이 적는 것이 컨벤션입니다.

2023-03-31 04:06 UTC, korjun1993 commented on app/src/main/java/com/hotelJava/member/error/errorCode/MemberErrorCode.java
> +  DuplicateEmailFound(409, "Email already exists");
넵 찾아보니 enum은 상수 컨벤션을 따라야하는군요..

2023-03-31 04:17 UTC, merged