[#6] 숙소 조회 기능 추가
f-lab-edu/hotel-java pull request #7
Opened 2023-03-26 11:10 UTC by DevKTak

PR 요청 드립니다.

2023-04-02 09:55 UTC, f-lab-scott requested changes
꼼꼼한 테스트 케이스와 새로운 시도들 좋습니다. 👍 
강의에서 다뤄볼 사항들은 잠시 후에 함께 말씀 나눠보면 좋겠습니다.

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/controller/AccommodationController.java
> +    return "test";
무엇을 위한 테스트입니까? 이제 테스트는 없어도 될 것 같습니다 ^.~

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/controller/AccommodationController.java
> +      @PathVariable("type") String type,
여기서 바로 enum으로 받아도 될 듯 합니다.

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/controller/AccommodationController.java
> +//  }
주석은 제거 부탁드립니다!

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/domain/Accommodation.java
> +    @GeneratedValue
`strategy` 옵션이 없는데요, 혹시 이 옵션의 기본값과 각 옵션 별 작동에 대해 학습해 보시는 건 어떨까요?

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/domain/Accommodation.java
> +    private AccommodationPicture accommodationPicture;
아까 슬랙에서 얘기 나눈 구조대로라면, 조인칼럼은 `picture` 쪽에 있어야 할 거 같습니다~

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/domain/Accommodation.java
> +    private String thirdPhoneNumber;
오 이것의 용도 궁금합니다

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/domain/AccommodationPicture.java
> +public class AccommodationPicture extends BaseTimeEntity {
여기서도 수정이 일어난다고 생각하겠습니다.

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/domain/AccommodationType.java
> +  private final String value;
`value` 라는 키워드가 enum class가 기본적으로 갖고 있는 메소드들에서 자주 사용되는 표현인 만큼, 변수명을 조금 바꿔보시면 좋겠습니다. `label` 정도면 어떨까 싶긴하네요

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/dto/AccommodationRequestDto.java
> +import jakarta.validation.constraints.NotBlank;
밸리데이션 적절히 사용해 주신 것 너무 좋네요! 👍

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/exception/AccommodationExceptionHandler.java
> +    @ExceptionHandler(DuplicatedAccommodationNameException.class)
요런 커스텀 예외들의 최상위에 위차하는 하나의 커스텀 예외를 두고요, 그 예외를 활용해서 좀 더 넓은 범위의 controller advice를 작성해주시면 좋을 것 같은데요,
댓글로 표현하니 어려운데 이따 미팅 시간에 좀 다뤄보겠습니다~

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/exception/DuplicatedAccommodationNameException.java
> +    }
사용할 것 같은 생성자만 구현해주시면 됩니다!

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/repository/AccommodationRepository.java
> +@Transactional(readOnly = true)
레포지토리에 전역적으로 `@Transactional` 붙이는 것인 비추합니다. 

- 확장에 열려있지 않습니다. 레포지토리의 본래 기능을 제한하는 꼴이 됩니다.
- 어차피 레포지토리의 영역까지는 영속성 콘텍스트가 열려있습니다. 요 애노테이션은 레포지토리 밖으로 그것을 확장하기 위해 사용하는 것입니다.

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/reservation/domain/Reservation.java
> +    private String phoneNumber;
요 패턴이 반복되는 것 같은데, 하나의 오브젝트로 뺄 순 없으려나요?

2023-04-02 09:55 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/reservation/domain/Reservation.java
> +    }
이것을 생성하는 로직은 엔티티와는 무관하게 관리되어야 할 것 같단 생각이 드는데, 어떠신가요?
의존성 주입 등을 통해 로직이 관리되어야 할 것 같습니다.

2023-04-02 12:04 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/exception/AccommodationExceptionHandler.java
> +    @ExceptionHandler(DuplicatedAccommodationNameException.class)
```java
@ExceptionHandler(CommonException.class)

2023-04-02 12:10 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/exception/DuplicatedAccommodationNameException.java
> +    }
```java
public DuplicatedAccommodationNameException() {
    super("중복된 숙박 업소 이름입니다.");
}

2023-04-02 12:11 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/exception/DuplicatedAccommodationNameException.java
> +public class DuplicatedAccommodationNameException extends RuntimeException {
```java
public CommonException {
    private int statusCode;

    public CommonException(String message, int statusCode) {
        this.statusCode = statusCode;
        super(message);
    }
}

2023-04-02 12:16 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/exception/DuplicatedAccommodationNameException.java
> +public class DuplicatedAccommodationNameException extends RuntimeException {
```java
public enum ErrorCode {

    // 회원 관련 에러
    MEMBER_BAD_REQUEST("잘못된 회원 요청입니다", 400),
    DUPLICATED_NAME(...),
    BAD_PASSWORD(...),

    //숙소 관련 에러
    ACCOMMODATION_BAD_REQUEST(..),
    DUPLICATED_ACCOMODATION_NAME(...)

2023-04-02 12:18 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/exception/DuplicatedAccommodationNameException.java
> +public class DuplicatedAccommodationNameException extends RuntimeException {
```java
public MemberException(ErrorCode code, String reason) {
    super(code.message, code.statusCode);
    this.reason = reason;
}

2023-04-02 12:27 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/reservation/domain/Reservation.java
> +    }
```java
public class TestReservationNumberGenerator implements ReservationNumberGenerator {
    
    @Override
    public String generateReservationNumber() {
        return "test";
    }
}

2023-04-02 12:28 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/reservation/domain/Reservation.java
> +    }
```java
public class UUIDReservationNumberGenerator implements ReservationNumberGenerator {
    
    @Override
    public String generateReservationNumber() {
        return UUID.randomUUID().toString();
    }
}

2023-04-04 10:33 UTC, DevKTak commented on app/src/main/java/com/hotelJava/accommodation/controller/AccommodationController.java
> +    return "test";
제거 하였습니다.

2023-04-04 10:39 UTC, DevKTak commented on app/src/main/java/com/hotelJava/accommodation/domain/Accommodation.java
> +    @GeneratedValue
Hibernate 5.0 이후 버전부터 키 생성 전략 MySQL AUTO가 IDENTITY에서 TABLE로 변경 되었습니다.
저희 프로젝트의 Hibernate 버전은 6점대 이기때문에  MySQL의 auto_increment 기능을 사용하기 위해 @GeneratedValue 애노테이션의 속성에 strategy = GenerationType.IDENTITY를 명시하는 것으로 수정하였습니다.

2023-04-04 10:40 UTC, DevKTak commented on app/src/main/java/com/hotelJava/accommodation/domain/AccommodationType.java
> +  private final String value;
label로 수정하였습니다.

2023-04-04 10:41 UTC, DevKTak commented on app/src/main/java/com/hotelJava/accommodation/exception/DuplicatedAccommodationNameException.java
> +    }
사용하는 생성자를 제외하고 삭제하였습니다.

2023-04-04 10:51 UTC, DevKTak commented on app/src/main/java/com/hotelJava/reservation/domain/Reservation.java
> +    }
- 엔티티와 무관한 로직을 분리하였습니다.
- 제어할 수 없는 코드에 의존하지 않고 인터페이스에 있는 메소드에만 의존하여 확장이 가능하도록 수정하였습니다.

2023-04-07 13:39 UTC, f-lab-scott requested changes
수고 많으셨습니다. 몇 가지 의견 드릴게요. 금방 고치실 수 있을 겁니다.

2023-04-07 13:39 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/controller/AccommodationController.java
> +      @RequestParam(required = false, defaultValue = "#{T(java.time.LocalDate).now().plusDays(1)}")
오 `defaultValue` 사용 상당히 좋습니다. 👍

2023-04-07 13:39 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/domain/Accommodation.java
> +  // == 연관관계 편의 메소드 ==//
👍

2023-04-07 13:39 UTC, f-lab-scott commented on app/src/main/java/com/hotelJava/accommodation/service/AccommodationService.java
> +      }
https://uchupura.tistory.com/32 
이 링크 보시고 stream API 기반으로 개선 시도해보시죠

2023-04-09 09:06 UTC, DevKTak commented on app/src/main/java/com/hotelJava/accommodation/controller/AccommodationController.java
> +      @RequestParam(required = false, defaultValue = "#{T(java.time.LocalDate).now().plusDays(1)}")
감사합니다!

2023-04-09 09:07 UTC, DevKTak commented on app/src/main/java/com/hotelJava/accommodation/service/AccommodationService.java
> +      }
넵!

2023-04-09 12:44 UTC, merged